### ISSUE TITLE
Unusual comments?

### ISSUE THREAD

**Issue by sgalcheung** [syhily/yufan.me#51]
When I add a comment, it is successful but not successful!
![image](https://github.com/syhily/yufan.me/assets/42566429/cf428452-bc2f-459c-a98f-21dc48485207)

my comment just now moved the comment control, isn't it blow the comment control?

**Comment by sgalcheung** [comment]
![image](https://github.com/syhily/yufan.me/assets/42566429/e4f8a1e2-4034-4e85-be5c-0e8aac28ced7)

Maybe, this li tag should be put into the ul tag, and displayed first comment.

**Comment by sgalcheung** [comment]
Maybe we can use [slots](https://docs.astro.build/en/reference/container-reference/#slots) to resolve this problem.

**Comment by syhily** [comment]
Thanks for finding this bug. Your comments are dynamically appended to the comment list after posting. It's not rendered at the backend. This assertion should be changed to `if (request.rid !== 0) {`

https://github.com/syhily/yufan.me/blob/cd7863c557816b2139f8cc278887e441fac73f5d/src/assets/scripts/yufan.me.js#L223C19-L223C22
