### ISSUE TITLE
This repo build error

### ISSUE THREAD

**Issue by sgalcheung** [syhily/yufan.me#52]
I did the following, and it went wrong.

```
npm install
npm run build
```

> ❯ npm run build
> 
> > yufan.me@3.0.0 build
> > rimraf dist && astro check && astro build
> 
> 12:14:23 [types] Added src/env.d.ts type declarations.
> 12:14:24 [types] Added src/env.d.ts type declarations.
> 12:14:24 Types generated 746ms
> 12:14:24 [check] Getting diagnostics for Astro files in  .../yufan.me...
> Result (87 files): 
> - 0 errors
> - 0 warnings
> - 0 hints
> 
> 12:14:35 [WARN] [config] The feature "astro:env getSecret" is experimental and subject to change (used by @astrojs/node).
> 12:14:35 [types] Added src/env.d.ts type declarations.
> 12:14:35 [vite] Re-optimizing dependencies because vite config has changed
> 12:14:36 [types] Added src/env.d.ts type declarations.
> 12:14:36 [build] output: "server"
> 12:14:36 [build] directory: .../yufan.me/dist/
> 12:14:36 [build] adapter: @astrojs/node
> 12:14:36 [build] Collecting build info...
> 12:14:36 [build] ✓ Completed in 789ms.
> 12:14:36 [build] Building server entrypoints...
> 12:14:36 [types] Added src/env.d.ts type declarations.
> 12:14:48 [vite] ✓ built in 11.72s
> 12:14:48 [build] ✓ Completed in 11.79s.
> 
>  building client (vite) 
> 12:14:48 [types] Added src/env.d.ts type declarations.
> 12:14:48 [vite] ✓ 12 modules transformed.
> 12:14:52 [vite] dist/client/cats/hoisted.C48bVZ4-.js  76.52 kB │ gzip: 19.84 kB
> 12:14:52 [vite] ✓ built in 4.11s
> 
>  prerendering static routes 
> 12:14:54 λ src/pages/og/[slug].png.ts
> 12:14:54   ├─ /og/gossip-on-reading.png (+662ms)
> 12:14:55   ├─ /og/algo-find-the-lowest-costs.png (+799ms)
> 12:14:56   ├─ /og/about-hefei.png (+1.05s)
> 12:14:57   ├─ /og/switch-blog-to-nextjs.png (+919ms)
> 12:14:58   ├─ /og/basic-terms-in-book-binding.png (+752ms)
> 12:14:58   ├─ /og/a-letter-for-myself-after-ten-years.png (+827ms)
> 12:14:59   ├─ /og/the-middle-age.png (+998ms)
> 12:15:00   ├─ /og/afternoon-rhapsody.png (+1.59s)
> 12:15:02   ├─ /og/memory-of-diary-letter-and-notes.png (+1.53s)
> 12:15:03   ├─ /og/peter-pan-in-my-heart.png (+1.05s)
> 12:15:04   ├─ /og/could-educate-make-us-better.png (+1.11s)
> 12:15:06   ├─ /og/round-bowl.png (+970ms)
> 12:15:07   ├─ /og/the-sun-in-march.png (+1.05s)
> 12:15:08   ├─ /og/gossiping-on-winter.png (+1.04s)
> 12:15:09   ├─ /og/blind-date-review.png (+932ms)
> 12:15:10   ├─ /og/wagahaihanekodearu.png (+1.04s)
> 12:15:11   ├─ /og/hanabi-ga-hana-jyanai.png (+1.03s)
> 12:15:12   ├─ /og/three-stage-of-programming.png (+1.00s)
> 12:15:13   ├─ /og/teruteru-2.png (+784ms)
> 12:15:13   ├─ /og/teruteru-1.png (+1.13s)
> 12:15:15   ├─ /og/leave-some-by-myself.png (+960ms)
> 12:15:16   ├─ /og/watashitachi-ha-mokuzaidesu.png (+836ms)
> 12:15:16   ├─ /og/first-three-month-in-oneapm.png (+1.09s)
> 12:15:17   ├─ /og/two-years-in-oneapm.png (+911ms)
> 12:15:18   ├─ /og/evolution-of-data-structures-in-yandex-metrica.png (+599ms)
> 12:15:19   ├─ /og/rain-in-august.png (+942ms)
> 12:15:20   ├─ /og/atelier-firis-first-year-walk-through.png (+1.17s)
> 12:15:21   ├─ /og/springboot-brief-intro.png (+546ms)
> 12:15:22   ├─ /og/yume.png (+902ms)
> 12:15:23   ├─ /og/rewrite-your-logic.png (+863ms)
> 12:15:23   ├─ /og/a-scala-exercise-a-day-1.png (+1.00s)
> 12:15:24   ├─ /og/future-plan-on-kids.png (+931ms)
> 12:15:25   ├─ /og/summer-dream.png (+1.90s)
> 12:15:27   ├─ /og/my-fickleness-life.png (+1.06s)
> 12:15:28   ├─ /og/how-to-read-a-technology-book.png (+691ms)
> 12:15:29   ├─ /og/primary-school-student.png (+861ms)
> 12:15:30   ├─ /og/introduction-to-webpack-part-1.png (+263ms)
> 12:15:30   ├─ /og/forget-past.png (+686ms)
> 12:15:31   ├─ /og/just-try.png (+382ms)
> 12:15:31   ├─ /og/work-summary.png (+487ms)
> 12:15:32   ├─ /og/oauth-on-kong.png (+1.04s)
> 12:15:33   ├─ /og/dumplings-in-winter-solstice.png (+1.10s)
> 12:15:34   ├─ /og/rest-api-design.png (+386ms)
> 12:15:34   ├─ /og/we-are-stranger.png (+1.04s)
> 12:15:35   ├─ /og/gossip-on-profligate-spending.png (+2.44s)
> 12:15:38   ├─ /og/how-to-choose-your-tools.png (+1.13s)
> 12:15:39   ├─ /og/i-am-right-here.png (+2.36s)
> 12:15:41   ├─ /og/having-a-lomo-life.png (+1.29s)
> 12:15:42   ├─ /og/lets-married.png (+763ms)
> 12:15:43   ├─ /og/the-better-way-to-make-objects.png (+361ms)
> 12:15:44   ├─ /og/this-is-the-linux.png (+797ms)
> 12:15:44   ├─ /og/the-first-week-of-accession.png (+1.17s)
> 12:15:46   ├─ /og/my-university-life.png (+473ms)
> 12:15:46   ├─ /og/the-poem-of-forget.png (+867ms)
> 12:15:47   ├─ /og/black-history-of-my-childhood.png (+1.07s)
> 12:15:48   ├─ /og/the-things-you-dont-know.png (+851ms)
> 12:15:49   ├─ /og/grown-old-with-a-age.png (+1.02s)
> 12:15:50   ├─ /og/meeting.png (+1.03s)
> 12:15:51   ├─ /og/the-poor-efficiency-of-android-program.png (+648ms)
> 12:15:52   ├─ /og/wretched-history-of-my-childhood.png (+968ms)
> 12:15:52   ├─ /og/see-it-or-not.png (+864ms)
> 12:15:53   ├─ /og/change-it-or-not.png (+795ms)
> 12:15:54   ├─ /og/mid-autumn-festival.png (+851ms)
> 12:15:55   ├─ /og/fear-of-death.png (+555ms)
> 12:15:56   ├─ /og/the-moonlight-in-city.png (+716ms)
> 12:15:56   ├─ /og/afternoon-nap.png (+1.15s)
> 12:15:57   ├─ /og/summer-training-record.png (+1.09s)
> 12:15:59   ├─ /og/unwilling-to-grow-old.png (+773ms)
> 12:15:59   ├─ /og/those-people.png (+835ms)
> 12:16:00   ├─ /og/lost-myself-in-may-day.png (+867ms)
> 12:16:01   ├─ /og/the-girl-who-leave-you.png (+1.01s)
> 12:16:02   ├─ /og/whose-youth-do-not-have-a-shallow-bruising.png (+1.28s)
> 12:16:03   ├─ /og/the-best-way-to-learn-css.png (+278ms)
> 12:16:04   ├─ /og/spring-essay.png (+1.61s)
> 12:16:05   ├─ /og/trivial-thought.png (+822ms)
> 12:16:06   ├─ /og/pushu-and-his-flower.png (+773ms)
> 12:16:07   ├─ /og/gray-avatar.png (+900ms)
> 12:16:08   ├─ /og/tender-feeling.png (+962ms)
> 12:16:09   ├─ /og/choices.png (+778ms)
> 12:16:09   ├─ /og/when-i-was-young.png (+806ms)
> 12:16:10   ├─ /og/sad-melody.png (+686ms)
> 12:16:11   ├─ /og/never-stop-writing.png (+1.09s)
> 12:16:12   ├─ /og/secret-of-boys-mind.png (+1.14s)
> 12:16:13   ├─ /og/lend-me-more-time.png (+802ms)
> 12:16:14   ├─ /og/the-meaning-of-independency.png (+663ms)
> 12:16:15   ├─ /og/the-third-year-of-loney.png (+813ms)
> 12:16:15   ├─ /og/the-elegant-past.png (+1.11s)
> 12:16:16   ├─ /og/cherry-blossoms.png (+947ms)
> 12:16:17   ├─ /og/ccf-meeting.png (+1.13s)
> 12:16:19   ├─ /og/the-memory-of-smell.png (+1.42s)
> 12:16:20   ├─ /og/i-love-you-forever.png (+890ms)
> 12:16:21   ├─ /og/the-feeling-of-love.png (+786ms)
> 12:16:22   ├─ /og/hello-tomorrow.png (+757ms)
> 12:16:22   ├─ /og/two-miscellany.png (+1.46s)
> 12:16:24   ├─ /og/where-is-my-dream.png (+707ms)
> 12:16:25   ├─ /og/the-season-of-walking.png (+1.27s)
> 12:16:26   ├─ /og/the-forgotten-accent.png (+843ms)
> 12:16:27   ├─ /og/scattered-fireworks.png (+1.56s)
> 12:16:28   ├─ /og/the-first-year-of-blogging.png (+2.33s)
> 12:16:31   ├─ /og/koto-no-ha-no-niwa.png (+893ms)
> 12:16:31   ├─ /og/greedy-children.png (+1.45s)
> 12:16:33   ├─ /og/novel-story-3.png (+1.03s)
> 12:16:34   ├─ /og/philosophy-and-thinking.png (+1.34s)
> 12:16:35   ├─ /og/goodbye-youth.png (+1.42s)
> 12:16:37   ├─ /og/fathers-love.png (+834ms)
> 12:16:38   ├─ /og/sunset.png (+2.01s)
> 12:16:40   ├─ /og/the-misspelled-word.png (+1.05s)
> 12:16:41   ├─ /og/happiness-caprice.png (+814ms)
> 12:16:41   ├─ /og/evening-caprice.png (+1.38s)
> 12:16:43   ├─ /og/our-mtimes.png (+726ms)
> 12:16:44   ├─ /og/my-darling.png (+844ms)
> 12:16:44   ├─ /og/nocturne.png (+922ms)
> 12:16:45   ├─ /og/growing-pains.png (+1.01s)
> 12:16:46   ├─ /og/anonaha.png (+1.67s)
> 12:16:48   ├─ /og/graduation-season-farewell-season.png (+1.17s)
> 12:16:49   ├─ /og/summer-air.png (+959ms)
> 12:16:50   ├─ /og/your-city-my-dream.png (+1.00s)
> 12:16:51   ├─ /og/my-grandpa.png (+477ms)
> 12:16:52   ├─ /og/essay-of-spring.png (+1.81s)
> 12:16:53   ├─ /og/one-more-time.png (+1.24s)
> 12:16:55   ├─ /og/mothers-day.png (+735ms)
> 12:16:55   ├─ /og/novel-story-2.png (+859ms)
> 12:16:56   ├─ /og/novel-story-1.png (+820ms)
> 12:16:57   ├─ /og/novel-story-0.png (+818ms)
> 12:16:58   ├─ /og/the-flavour-of-sunshine.png (+860ms)
> 12:16:59   ├─ /og/your-second-home.png (+1000ms)
> 12:17:00   ├─ /og/the-first-day-of-bns-cbt3.png (+727ms)
> 12:17:00   ├─ /og/the-bns-cbt3.png (+844ms)
> 12:17:01   ├─ /og/dragon-nest.png (+1.51s)
> 12:17:03   ├─ /og/chirography-on-letter.png (+769ms)
> 12:17:04   ├─ /og/left-time-right-live.png (+939ms)
> 12:17:05   ├─ /og/bougainvillea-spectabilis-willd.png (+1.55s)
> 12:17:06   ├─ /og/when-u-were-young.png (+1.02s)
> 12:17:07   ├─ /og/the-poem-of-nalansingde.png (+859ms)
> 12:17:08   ├─ /og/the-wounds-of-the-tree.png (+983ms)
> 12:17:09   ├─ /og/at-home.png (+1.23s)
> 12:17:10   ├─ /og/walk-on-playground.png (+981ms)
> 12:17:11   ├─ /og/strangeness.png (+1.01s)
> 12:17:12   ├─ /og/old-house.png (+773ms)
> 12:17:13   ├─ /og/take-the-train.png (+963ms)
> 12:17:14   ├─ /og/intimate-in-mind.png (+1.08s)
> 12:17:15   ├─ /og/spring-words.png (+1.13s)
> 12:17:16   ├─ /og/image-times.png (+1.16s)
> 12:17:17   ├─ /og/blue-turkey.png (+1.22s)
> 12:17:18   ├─ /og/my-dear-kitty.png (+1.26s)
> 12:17:20   ├─ /og/visitant.png (+754ms)
> 12:17:20   ├─ /og/the-stopped-wheelchair.png (+1.01s)
> 12:17:22   ├─ /og/who-is-singing.png (+1.37s)
> 12:17:23   ├─ /og/one-hundred-days.png (+893ms)
> 12:17:24   ├─ /og/sauvignon-blanc.png (+959ms)
> 12:17:25   ├─ /og/you-are-the-apple-of-mine.png (+972ms)
> 12:17:26   ├─ /og/drink-the-tea.png (+840ms)
> 12:17:27   ├─ /og/the-first-snowing.png (+634ms)
> 12:17:27   ├─ /og/restart-the-blog.png (+1.06s)
> 12:17:28   ├─ /og/the-amber-in-november.png (+913ms)
> 12:17:29   ├─ /og/sunny-day-after-rain.png (+878ms)
> 12:17:30   ├─ /og/explorer-keyboard.png (+611ms)
> 12:17:31   ├─ /og/south-or-north.png (+750ms)
> 12:17:31   ├─ /og/face-the-fact.png (+843ms)
> 12:17:32   ├─ /og/show-the-sword.png (+540ms)
> 12:17:33   ├─ /og/the-streets-where-wind-lives.png (+666ms)
> 12:17:33   ├─ /og/loving-notebook.png (+513ms)
> 12:17:34   ├─ /og/the-centenary-of-school-anniversary.png (+1.07s)
> 12:17:35   ├─ /og/im-a-male-not-female.png (+673ms)
> 12:17:36   ├─ /og/memories-of-blossom.png (+837ms)
> 12:17:37   ├─ /og/past-memory.png (+881ms)
> 12:17:37   ├─ /og/those-words-my-love.png (+876ms)
> 12:17:38   ├─ /og/the-story-of-time.png (+1.01s)
> 12:17:39   ├─ /og/countercurrent-river.png (+808ms)
> 12:17:40   ├─ /og/the-losted-beautiful.png (+986ms)
> 12:17:41   ├─ /og/shallow-lonely-faint-miss.png (+1.09s)
> 12:17:42   ├─ /og/harry-potter.png (+814ms)
> 12:17:43   ├─ /og/floral-sarong.png (+836ms)
> 12:17:44   ├─ /og/ignorant-age.png (+838ms)
> 12:17:45   ├─ /og/bathe.png (+916ms)
> 12:17:46   ├─ /og/the-pain-of-lonely.png (+922ms)
> 12:17:47   ├─ /og/hear-the-wind-sing.png (+1.62s)
> 12:17:48   ├─ /og/association-of-old-books.png (+858ms)
> 12:17:49   ├─ /og/the-beginning-of-blog.png (+839ms)
> 12:17:50   ├─ /og/drip-records.png (+1.28s)
> 12:17:51   ├─ /og/19-year-old.png (+1.07s)
> 12:17:52   ├─ /og/old-train-site.png (+1.07s)
> 12:17:53   ├─ /og/cherry-blossoms-withered.png (+970ms)
> 12:17:54   ├─ /og/swan-of-thought.png (+793ms)
> 12:17:55   ├─ /og/phoenix-flowers.png (+2.36s)
> 12:17:57   ├─ /og/about.png (+921ms)
> 12:17:58   ├─ /og/guestbook.png (+882ms)
> 12:17:59   └─ /og/links.png (+865ms)
> 12:17:56 λ src/pages/sitemap.xml.ts
> 12:17:56   └─ /sitemap.xml (+2ms)
> 12:17:56 ✓ Completed in 187.81s.
> 
> 12:17:56 
>  finalizing server assets 
> 
> 12:17:56 [build] Rearranging server assets...
> 12:17:56 [ERROR] [S3 Uploader] Uploader options validation error, there are 3 errors:
> 12:17:56 [ERROR] [S3 Uploader] Required
> 12:17:56 [ERROR] [S3 Uploader] Required
> 12:17:56 [ERROR] [S3 Uploader] Required
> Required
>   Stack trace:
>     at get error [as error] (file:///Users/sgalcheung/Documents/200%20-%20%E5%B7%A5%E4%BD%9C%EF%BC%88Work%EF%BC%89/240%20-%20%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88%EF%BC%88Solution%EF%BC%89/243%20-%20%E5%8D%9A%E5%AE%A2%EF%BC%88Blog%EF%BC%89/243.1%20-%20%E5%8D%9A%E5%AE%A2%E6%A8%A1%E7%89%88%EF%BC%88Blog%20Template%EF%BC%89/yufan.me/node_modules/zod/lib/index.mjs:587:31)
>     at parseOptions (eval at instantiateModule (file:///Users/sgalcheung/Documents/200%20-%20%E5%B7%A5%E4%BD%9C%EF%BC%88Work%EF%BC%89/240%20-%20%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88%EF%BC%88Solution%EF%BC%89/243%20-%20%E5%8D%9A%E5%AE%A2%EF%BC%88Blog%EF%BC%89/243.1%20-%20%E5%8D%9A%E5%AE%A2%E6%A8%A1%E7%89%88%EF%BC%88Blog%20Template%EF%BC%89/yufan.me/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:53398:24), <anonymous>:39:22)
>     at runHookBuildDone (file:///Users/sgalcheung/Documents/200%20-%20%E5%B7%A5%E4%BD%9C%EF%BC%88Work%EF%BC%89/240%20-%20%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88%EF%BC%88Solution%EF%BC%89/243%20-%20%E5%8D%9A%E5%AE%A2%EF%BC%88Blog%EF%BC%89/243.1%20-%20%E5%8D%9A%E5%AE%A2%E6%A8%A1%E7%89%88%EF%BC%88Blog%20Template%EF%BC%89/yufan.me/node_modules/astro/dist/integrations/hooks.js:409:58)
>     at async AstroBuilder.run (file:///Users/sgalcheung/Documents/200%20-%20%E5%B7%A5%E4%BD%9C%EF%BC%88Work%EF%BC%89/240%20-%20%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88%EF%BC%88Solution%EF%BC%89/243%20-%20%E5%8D%9A%E5%AE%A2%EF%BC%88Blog%EF%BC%89/243.1%20-%20%E5%8D%9A%E5%AE%A2%E6%A8%A1%E7%89%88%EF%BC%88Blog%20Template%EF%BC%89/yufan.me/node_modules/astro/dist/core/build/index.js:164:7)
>     at async build (file:///Users/sgalcheung/Documents/200%20-%20%E5%B7%A5%E4%BD%9C%EF%BC%88Work%EF%BC%89/240%20-%20%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88%EF%BC%88Solution%EF%BC%89/243%20-%20%E5%8D%9A%E5%AE%A2%EF%BC%88Blog%EF%BC%89/243.1%20-%20%E5%8D%9A%E5%AE%A2%E6%A8%A1%E7%89%88%EF%BC%88Blog%20Template%EF%BC%89/yufan.me/node_modules/astro/dist/cli/build/index.js:20:3)

**Comment by syhily** [comment]
This is not a bug. It's a S3 integration for uploading the building materials to a cloud OSS service. You should comment the uploader configuration [here](https://github.com/syhily/yufan.me/blob/cd7863c557816b2139f8cc278887e441fac73f5d/astro.config.ts#L39)

**Comment by syhily** [comment]
Remember to modify the [options.ts](https://github.com/syhily/yufan.me/blob/astro/options.ts) if you want to build your own blog on top of this source code.
